version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ot-network

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      REDIS_URL: redis://redis:6379
    networks:
      - ot-network

  engine:
    build: ./engine
    container_name: engine
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      REDIS_URL: redis://redis:6379
    networks:
      - ot-network

  websocket:
    build: ./websocket
    container_name: websocket
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      REDIS_URL: redis://redis:6379
    networks:
      - ot-network

networks:
  ot-network:
    driver: bridge
